const Environment = () => {
    return {
        SOK_FORELDREPENGER_URL: global.appSettings.SOK_FORELDREPENGER_URL,
        SOK_FORELDREPENGER_PAPIR_URL: global.appSettings.SOK_FORELDREPENGER_PAPIR_URL,
        SOK_ENGANGSSTONAD_URL: global.appSettings.SOK_ENGANGSSTONAD_URL,
        SOK_ENGANGSSTONAD_PAPIR_URL: global.appSettings.SOK_ENGANGSSTONAD_PAPIR_URL,
        DINE_FORELDREPENGER_URL: global.appSettings.DINE_FORELDREPENGER_URL,
        SOK_SVANGERSKAPSPENGER_URL: global.appSettings.SOK_SVANGERSKAPSPENGER_URL,
        SOK_SVANGERSKAPSPENGER_PAPIR_URL: global.appSettings.SOK_SVANGERSKAPSPENGER_PAPIR_URL,
        PLANLEGGEREN_URL: global.appSettings.PLANLEGGEREN_URL
    };
};

export default Environment();
